import React, { useState } from "react";
import { BackButton } from "../components/Shared";
import { loginPartner, registerPartner } from "../api/partners";
type Role = "courier" | "owner";
const Field = ({ label, value, set, type = "text", placeholder }: { label: string; value: string; set: (v: string) => void; type?: string; placeholder?: string }) => <label className="block text-sm font-semibold">{label}<input required type={type} value={value} onChange={e => set(e.target.value)} placeholder={placeholder} className="mt-1.5 w-full rounded-xl border border-[var(--border)] bg-white px-4 py-3 font-normal outline-none focus:border-[var(--green)]" /></label>;
export default function RoleApplicationScreen({ role, onAuthenticated }: { role: Role; onAuthenticated?: (role: Role) => void }) {
  const [tab, setTab] = useState<"login" | "register">("login"), [nickname, setNickname] = useState(""), [password, setPassword] = useState(""), [fullName, setFullName] = useState(""), [phone, setPhone] = useState(""), [address, setAddress] = useState(""), [restaurantName, setRestaurantName] = useState(""), [identityNumber, setIdentityNumber] = useState(""), [businessRegistrationNumber, setBusinessRegistrationNumber] = useState(""), [driverLicense, setDriverLicense] = useState(""), [vehiclePlate, setVehiclePlate] = useState(""), [vehicleRegistration, setVehicleRegistration] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setBusy(true); setMessage(""); try { if (tab === "login") { await loginPartner({ role, nickname, password }); onAuthenticated?.(role); } else { await registerPartner({ role, nickname, password, fullName, phone, address, documents: role === "courier" ? { driverLicense, vehiclePlate, vehicleRegistration } : { restaurantName, identityNumber, businessRegistrationNumber } }); setMessage("Ariza yuborildi. Admin tasdiqlagach nickname va parol bilan kira olasiz."); setTab("login"); } } catch (error) { setMessage(error instanceof Error ? error.message : "Xato yuz berdi"); } finally { setBusy(false); } };
  return <div className="flex h-full flex-col bg-[var(--cream)]"><header className="flex items-center gap-3 border-b bg-white p-4"><BackButton/><h1 className="text-lg font-bold">{role === "courier" ? "Kuryer portali" : "Oshxona egasi portali"}</h1></header><div className="phone-scroll flex-1"><form onSubmit={submit} className="mx-auto w-full max-w-2xl space-y-5 p-6">
    <div className="grid grid-cols-2 rounded-xl bg-white p-1">{(["login", "register"] as const).map(v => <button type="button" key={v} onClick={() => { setTab(v); setMessage(""); }} className={`rounded-lg py-2.5 text-sm font-bold ${tab === v ? "bg-[var(--green)] text-white" : "text-[var(--muted)]"}`}>{v === "login" ? "Kirish" : "Ro‘yxatdan o‘tish"}</button>)}</div>
    <Field label="Nickname" value={nickname} set={setNickname} placeholder="Kamida 3 belgi"/><Field label="Parol" type="password" value={password} set={setPassword} placeholder="Kamida 8 belgi"/>
    {tab === "register" && <><Field label={role === "courier" ? "Kuryerning ism-familiyasi" : "Oshxona egasining ism-familiyasi"} value={fullName} set={setFullName}/><Field label="Telefon raqami" value={phone} set={setPhone}/><Field label={role === "courier" ? "Uy manzili" : "Oshxona manzili"} value={address} set={setAddress}/>{role === "courier" ? <><Field label="Haydovchilik guvohnomasi raqami" value={driverLicense} set={setDriverLicense}/><Field label="Avtomobil davlat raqami" value={vehiclePlate} set={setVehiclePlate} placeholder="12가3456"/><Field label="Transport ro‘yxatdan o‘tganlik hujjati raqami" value={vehicleRegistration} set={setVehicleRegistration}/></> : <><Field label="Oshxona nomi" value={restaurantName} set={setRestaurantName}/><Field label="Shaxsni tasdiqlovchi ID raqami" value={identityNumber} set={setIdentityNumber}/><Field label="사업자등록번호 — biznes ro‘yxat raqami" value={businessRegistrationNumber} set={setBusinessRegistrationNumber} placeholder="000-00-00000"/></>}</>}
    <button disabled={busy} className="w-full rounded-xl bg-[var(--green)] py-3.5 font-bold text-white disabled:opacity-60">{busy ? "Tekshirilmoqda…" : tab === "login" ? "Ish paneliga kirish" : "Ro‘yxatdan o‘tish arizasini yuborish"}</button>{message && <p className="rounded-xl bg-white p-4 text-center text-sm font-semibold">{message}</p>}
  </form></div></div>;
}
