import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { writeFileSync } from 'node:fs';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 390, height: 900 } });
const base = process.env.TEST_BASE_URL || 'http://127.0.0.1:8443';
const passed = [];
const route = async path => { await page.goto(`${base}/#/customer/${path}`); await page.waitForTimeout(150); };
try {
  await page.goto(base);
  await page.getByRole('button', { name: 'Customer + admin paneli', exact: false }).click();
  await page.locator('button[type="submit"]').click();
  await page.locator('.customer-content').waitFor();
  await page.reload();
  await page.locator('.customer-content').waitFor();
  passed.push('API session survives reload');
  await route('restaurant-detail');
  await page.getByRole('button', { name: /^Saqlash:/ }).click();
  await route('saved-places');
  assert.equal(await page.getByRole('button', { name: /^Saqlangandan olib tashlash:/ }).count(), 1);
  await page.reload();
  await page.getByRole('button', { name: /^Saqlangandan olib tashlash:/ }).waitFor();
  passed.push('Favorites persist across routes and reload');
  await route('item-detail');
  await page.locator('textarea').fill('QA customization');
  await page.getByRole('button', { name: /장바구니 담기/ }).click();
  await page.waitForURL('**/#/customer/cart');
  assert.match(await page.locator('.customer-content').innerText(), /QA customization/);
  await route('menu');
  await page.getByRole('button', { name: '+', exact: true }).first().click();
  await route('cart');
  assert.match(await page.locator('.customer-content').innerText(), /QA customization/);
  await page.reload();
  await page.locator('.customer-content').waitFor();
  assert.match(await page.locator('.customer-content').innerText(), /QA customization/);
  passed.push('Menu quantity updates preserve customized cart items and reload state');
  await page.getByRole('button', { name: /주문하기/ }).last().click();
  await page.waitForURL('**/#/customer/checkout');
  await page.getByRole('button', { name: /Sinov|미리보기/ }).last().click();
  await page.waitForURL('**/#/customer/order-confirmation');
  await page.goBack();
  await page.waitForURL('**/#/customer/checkout');
  await page.goForward();
  await page.waitForURL('**/#/customer/order-confirmation');
  passed.push('Checkout preview and browser back/forward');
  await route('grocery');
  await page.getByRole('button', { name: /제품 보기/ }).first().click();
  assert.equal(await page.getByRole('button', { name: /savatga qo‘shish/ }).count(), 3);
  assert.equal(await page.getByRole('button', { name: /savatga qo‘shish/ }).last().isDisabled(), true);
  passed.push('Grocery tab and out-of-stock guard');
} finally {
  writeFileSync('plans/qa/flow-checks.json', JSON.stringify({ passed }, null, 2));
  console.log(passed);
  await browser.close();
}
